### ISSUE TITLE
本地运行

### ISSUE THREAD

**Issue by yaoshanliang** [devezhao/rktk-wxx#4]
本地运行无法拿到数据，配置小程序安全域名了。
![image](https://user-images.githubusercontent.com/5028569/45540485-2354a380-b83f-11e8-8d42-82f9643288de.png)

**Comment by yaoshanliang** [comment]
本地应该怎么运行？

**Comment by devezhao** [comment]
感谢关注。目前暂时没有后台提供，年后会提供一个后台服务供大家测试使用

**Comment by fahaihappy** [comment]
感谢开源，请问作者还有开源后台的打算吗？后台主要是用的什么框架和数据库？

**Comment by gocpplua** [comment]
> 。目前暂时没有后台提供，年后会提供一个后台服务供大家测试使用

你好，有测试环境吗

**Comment by fahaihappy** [comment]
您好  您的邮件我已收到   谢谢！！！

**Comment by gocpplua** [comment]
> 您好  您的邮件我已收到   谢谢！！！

你好，请问有测试环境吗
