### ISSUE TITLE
后台

### ISSUE THREAD

**Issue by fahaihappy** [devezhao/rktk-wxx#7]
感谢开源，请问作者还有开源后台的打算吗？后台主要是用的什么框架和数据库？

**Comment by 419768116** [comment]
感谢开源，请问作者还有开源后台的打算吗？后台主要是用的什么框架和数据库？

**Comment by dhaily** [comment]
感谢开源，请问作者还有开源后台的打算吗？后台主要是用的什么框架和数据库？
